name: Shared actions

on:
    workflow_dispatch:

jobs:
    checkout-repo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - run: ls 